var test1 = "false";
var test2 = true;
var test3 = { name: 'CTS' };
var test4 = [1, 2, 3];
var test5 = { name: 'Alex' };
var test6 = "Poonam";
console.log(test6);
console.log(typeof (test6));
// console.log(test5);
// console.log(typeof(test5));
test5 = true;
// console.log(typeof(test5));
// console.log(test1);
// console.log(test2);
// console.log(test3);
// console.log(test4);
// console.log(test1, test2);
